language: bash

os:
  - linux

branches:
  only:
  - master
  - develop

before_install:
  - wget https://storage.googleapis.com/shellcheck/shellcheck-latest.linux.x86_64.tar.xz
  - tar xf shellcheck-latest.linux.x86_64.tar.xz
  - ./shellcheck-latest/shellcheck --version

script:
  - bash -c 'shopt -s globstar; ./shellcheck-latest/shellcheck dep.sh'
  - bash -c 'shopt -s globstar; ./shellcheck-latest/shellcheck run.sh'
  - bash -c 'shopt -s globstar; ./shellcheck-latest/shellcheck self-update.sh'
  - bash -c 'shopt -s globstar; ./shellcheck-latest/shellcheck update.sh'
