language: bash

matrix:
  fast_finish: true

env:
  global:
    - SHELLCHECK_VERSION=0.7.1

branches:
  only:
  - master
  - develop

before_install:
  - wget https://github.com/koalaman/shellcheck/releases/download/v${SHELLCHECK_VERSION}/shellcheck-v${SHELLCHECK_VERSION}.linux.x86_64.tar.xz
  - tar xf shellcheck-v${SHELLCHECK_VERSION}.linux.x86_64.tar.xz
  - mv shellcheck-v${SHELLCHECK_VERSION} shellcheck-latest
  - ./shellcheck-latest/shellcheck --version

script:
  - bash -c 'shopt -s globstar; ./shellcheck-latest/shellcheck dep.sh'
  - bash -c 'shopt -s globstar; ./shellcheck-latest/shellcheck run.sh'
  - bash -c 'shopt -s globstar; ./shellcheck-latest/shellcheck self-update.sh'
  - bash -c 'shopt -s globstar; ./shellcheck-latest/shellcheck update.sh'
